package com.example.contatos.ui.theme

import androidx.compose.ui.graphics.Color

val BrandPrimaryLight = Color(0xFF3B5BDB)
val BrandOnPrimaryLight = Color(0xFFFFFFFF)
val BrandPrimaryContainerLight = Color(0xFFDDE4FF)
val BrandOnPrimaryContainerLight = Color(0xFF00174A)
val BrandSecondaryLight = Color(0xFF006C7C)
val BrandOnSecondaryLight = Color(0xFFFFFFFF)
val BrandSecondaryContainerLight = Color(0xFFAEEFFF)
val BrandOnSecondaryContainerLight = Color(0xFF001F26)
val BrandTertiaryLight = Color(0xFF6D4AFF)
val BrandBackgroundLight = Color(0xFFF7F9FD)
val BrandSurfaceLight = Color(0xFFF7F9FD)
val BrandSurfaceVariantLight = Color(0xFFE2E7F1)
val BrandOnSurfaceLight = Color(0xFF171C25)
val BrandOnSurfaceVariantLight = Color(0xFF434A58)
val BrandOutlineLight = Color(0xFF737B8A)
val SuccessLight = Color(0xFF166534)
val WarningLight = Color(0xFFB45309)
val ErrorLight = Color(0xFFBA1A1A)

val BrandPrimaryDark = Color(0xFFB8C4FF)
val BrandOnPrimaryDark = Color(0xFF032978)
val BrandPrimaryContainerDark = Color(0xFF2142C4)
val BrandOnPrimaryContainerDark = Color(0xFFDDE4FF)
val BrandSecondaryDark = Color(0xFF86D2E6)
val BrandOnSecondaryDark = Color(0xFF003640)
val BrandSecondaryContainerDark = Color(0xFF004E5D)
val BrandOnSecondaryContainerDark = Color(0xFFAEEFFF)
val BrandTertiaryDark = Color(0xFFD1C1FF)
val BrandBackgroundDark = Color(0xFF0F141C)
val BrandSurfaceDark = Color(0xFF0F141C)
val BrandSurfaceVariantDark = Color(0xFF434A58)
val BrandOnSurfaceDark = Color(0xFFEFF1F7)
val BrandOnSurfaceVariantDark = Color(0xFFC3C8D4)
val BrandOutlineDark = Color(0xFF8D94A3)
val SuccessDark = Color(0xFF7EE2A8)
val WarningDark = Color(0xFFF9C56D)
val ErrorDark = Color(0xFFFFB4AB)
